language: C

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpich2
  - sudo apt-get install -y cmake
  - which mpicc
  - pwd
  - ls
  - pushd /tmp

  - wget https://github.com/LLNL/json-cwx/archive/0.12.tar.gz
  - tar -xzf 0.12.tar.gz
  - pushd json-cwx-0.12/json-cwx
  - sh autogen.sh
  - ./configure --prefix=`pwd`/my_install
  - make -j4 install 1>/dev/null 2>&1
  - popd

  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
  - tar -xzf hdf5-1.8.14.tar.gz
  - pushd hdf5-1.8.14
  - ./configure --prefix=`pwd`/my_install --enable-production
  - make -j4 install 1>/dev/null 2>&1
  - popd

  - wget https://portal.nersc.gov/project/visit/releases/3.0.0b/third_party/silo-4.10.2.tar.gz
  - tar -xzf silo-4.10.2.tar.gz
  - pushd silo-4.10.2
  - ./configure --disable-hzip --disable-fpzip --disable-fortran --enable-install-lite-headers --prefix=`pwd`/my_install --with-hdf5=/tmp/hdf5-1.8.14/my_install/include,/tmp/hdf5-1.8.14/my_install/lib
  - make -j4 install 1>/dev/null 2>&1
  - popd

  - popd

install: true

script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_C_COMPILER:PATH=`which mpicc` -DCMAKE_CXX_COMPILER:PATH=`which mpicxx` -DWITH_JSON-CWX_PREFIX=/tmp/json-cwx-0.12/json-cwx/my_install -DENABLE_HDF5_PLUGIN=ON -DWITH_HDF5_PREFIX=/tmp/hdf5-1.8.14/my_install -DENABLE_PDB_PLUGIN=ON -DENABLE_SILO_PLUGIN=ON -DWITH_SILO_PREFIX=/tmp/silo-4.10.2/my_install ../.
  - make VERBOSE=1
  - make VERBOSE=1 check
  - ctest -V
